# Generated by Django 5.0.6 on 2025-10-07 02:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('students', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('CYBER', 'Cyber'), ('AI', 'IA'), ('DATA', 'Data'), ('DEVOPS', 'DevOps'), ('OTHER', 'Autre')], default='WEB', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Durée en jours')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('remote_allowed', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PUBLISHED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to='teams.team')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
                ('required_skills', models.ManyToManyField(blank=True, to='students.skill')),
            ],
        ),
    ]
