# Generated by Django 5.0.6 on 2025-10-07 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INFO', 'Info'), ('APPLICATION_SUBMITTED', 'Candidature envoyée'), ('APPLICATION_ACCEPTED', 'Candidature acceptée'), ('APPLICATION_REJECTED', 'Candidature refusée'), ('TEAM_INVITE', "Invitation d'équipe"), ('PAYMENT_SUCCEEDED', 'Paiement confirmé'), ('PROJECT_STATUS', 'Statut projet')], default='INFO', max_length=40)),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
